### ISSUE TITLE
Error Encountered While Loading Pretrained Model

### ISSUE THREAD

**Issue by fedeloper** [sanderwood/bgpt#3]
I appreciate your work and the resources provided. However, I encountered an error when attempting to load from a pretrained model. I configured the file as follows to align with the hyperparameters mentioned in your paper:

`PRETRAINED_PATH = "/home/fred/bgpt/weights-image.pth"                            # Path to pre-trained weights
WEIGHTS_PATH = "../weights/weights-image_new.pth"                        # Path to save weights
LOGS_PATH = "logs-imagenet.txt"                              # Path to save logs

# Configuration for the model
PATCH_SIZE = 16                                                 # Patch Size
PATCH_LENGTH = 512                                            # Patch Length
BYTE_NUM_LAYERS = 3                                             # Number of layers in the decoder
PATCH_NUM_LAYERS = 12                                           # Number of layers in the encoder
HIDDEN_SIZE = 768                                               # Hidden Size

# Configuration for the training
NUM_EPOCHS = 32                                                 # Number of epochs to train for (if early stopping doesn't intervene)
LEARNING_RATE = 1e-5                                            # Learning rate for the optimizer
BATCH_SIZE = 64                                                 # Batch size for training
ACCUMULATION_STEPS = 1                                          # Accumulation steps to simulate large batch size
PATCH_SAMPLING_BATCH_SIZE = 0                                   # Batch size for patch during training, 0 for full batch
LOAD_FROM_CHECKPOINT = False                                  # Whether to load weights from a checkpoint
LOAD_FROM_PRETRAINED = True                                    # Whether to load pre-trained weights from a checkpoint
CONVERSION_MODE = None                                          # Mode of conversion None for autoregressive training, 'input->output' for unidirectional conversion, 'input&output' for bidirectional conversion)
WANDB_LOG = True                                                # Whether to log to wandb
SHOW_WARNS = False                                              # Whether to show warnings
DETERMINISTIC = True   
 `

Despite this, I received the following error:

`/home/fred/bgpt/train-cls.py:254: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(PRETRAINED_PATH, map_location='cpu')
Traceback (most recent call last):
  File "/home/fred/bgpt/train-cls.py", line 263, in <module>
    pretrained_model.load_state_dict(checkpoint['model'])
  File "/home/fred/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for bGPTLMHeadModel:
        Unexpected key(s) in state_dict: "patch_level_decoder.base.h.0.attn.bias", "patch_level_decoder.base.h.0.attn.masked_bias", "patch_level_decoder.base.h.1.attn.bias", "patch_level_decoder.base.h.1.attn.masked_bias", "patch_level_decoder.base.h.2.attn.bias", "patch_level_decoder.base.h.2.attn.masked_bias", "patch_level_decoder.base.h.3.attn.bias", "patch_level_decoder.base.h.3.attn.masked_bias", "patch_level_decoder.base.h.4.attn.bias", "patch_level_decoder.base.h.4.attn.masked_bias", "patch_level_decoder.base.h.5.attn.bias", "patch_level_decoder.base.h.5.attn.masked_bias", "patch_level_decoder.base.h.6.attn.bias", "patch_level_decoder.base.h.6.attn.masked_bias", "patch_level_decoder.base.h.7.attn.bias", "patch_level_decoder.base.h.7.attn.masked_bias", "patch_level_decoder.base.h.8.attn.bias", "patch_level_decoder.base.h.8.attn.masked_bias", "patch_level_decoder.base.h.9.attn.bias", "patch_level_decoder.base.h.9.attn.masked_bias", "patch_level_decoder.base.h.10.attn.bias", "patch_level_decoder.base.h.10.attn.masked_bias", "patch_level_decoder.base.h.11.attn.bias", "patch_level_decoder.base.h.11.attn.masked_bias", "byte_level_decoder.base.transformer.h.0.attn.bias", "byte_level_decoder.base.transformer.h.0.attn.masked_bias", "byte_level_decoder.base.transformer.h.1.attn.bias", "byte_level_decoder.base.transformer.h.1.attn.masked_bias", "byte_level_decoder.base.transformer.h.2.attn.bias", "byte_level_decoder.base.transformer.h.2.attn.masked_bias". `
Could you kindly assist me in resolving this issue?

**Comment by sanderwood** [comment]
maybe you should check the version of transformers
